export const extCopy = {
  appName: "FCK FASCISTS",
  cleanState: "No political funding on record for this site.",
  donationUnavail: "Contribution data not available.",
  fecLink: "See FEC record \u2197",
  avoidBtn: "AVOID",
  snoozeBtn: "ZZZ SNOOZE 7d",
  avoidedTitle: "AVOIDED!",
  avoidedSub: "Nice!",
  weeklyTitle: "THIS WEEK",
  weeklyBiz: "BUSINESSES: ",
  weeklyPlat: "PLATFORMS: ",
  rPrefix: "R: ",
  dSep: " \u00b7 D: ",
  cyclePrefix: "in ",
  totalPrefix: "Total since 2016: R: ",
  activeCycles: "Active cycles: ",
  fecError: "Couldn\u2019t reach FEC.gov. Try again later.",
  noBundledData: "No contribution data on file.",
  confidenceHigh: "HIGH",
  confidenceMedium: "MEDIUM",
  mediumTitle: "MEDIUM confidence \u2014 verify at FEC.gov before acting.",
  mediumWarning: "MEDIUM confidence \u2014 verify before acting.",
  weeklyTop: "TOP: ",
} as const;
