export const extCopy = {
  appName: "F*CK FASCISTS",
  cleanState: "No flagged entities detected on this page.",
  donationUnavail: "Donation data temporarily unavailable.",
  fecLink: "See FEC record \u2197",
  avoidBtn: "\u2605 AVOIDED",
  snoozeBtn: "ZZZ SNOOZE 7d",
  avoidedTitle: "AVOIDED!",
  avoidedSub: "This one counts.",
  weeklyTitle: "THIS WEEK",
  weeklyBiz: "BUSINESSES: ",
  weeklyPlat: "PLATFORMS: ",
  gopPrefix: "GOP ",
  demSep: " \u00b7 DEM ",
  cyclePrefix: "in ",
  totalPrefix: "Total since 2016: GOP ",
  activeCycles: "Active cycles: ",
  fecError: "Couldn\u2019t reach FEC \u2014 try again later.",
  noBundledData: "No bundled donation data.",
  confidenceHigh: "HIGH",
  confidenceMedium: "MEDIUM",
  mediumTitle: "MEDIUM confidence \u2014 data may not be exact. Always verify at FEC.",
  mediumWarning: "MEDIUM confidence \u2014 verify before acting.",
  weeklyTop: "TOP: ",
} as const;
