export const betaCopy = {
  indicator: "BETA",
  indicatorLabel: "Beta testing mode is active",
  bugButton: "BUG",
  bugButtonLabel: "Report a bug — captures screenshot",
  resetButton: "RESET",
  resetButtonLabel: "Reset app state for a fresh-install style test",
  screenshotSaved: "Screenshot saved to camera roll.",
  screenshotFailed: "Could not save screenshot.",
  resetConfirmTitle: "Reset app for testing?",
  resetConfirmBody: "This clears onboarding, launch flags, platform setup, avoid history, and barcode cache so you can test from the beginning again.",
  resetCancelAction: "Cancel",
  resetConfirmAction: "Reset now",
  resetDone: "App state reset. Fully close and reopen the app to start from onboarding again.",
  resetFailed: "Could not reset app state.",
  activated: "Beta mode ON",
  deactivated: "Beta mode OFF",
} as const;
