export const infoCopy = {
  tabLabel: "INFO",
  title: "INFO",
  about: "ABOUT",
  data: "HOW IT WORKS",
  faq: "FAQ",
  links: "LINKS & SOURCE",
  linkText: (label: string) => `${label} \u2197`,
  linkLabel: (label: string) => `${label} \u2014 opens in browser`,
  faqCollapse: "Tap to collapse",
  faqExpand: "Tap to expand answer",
  chevronOpen: "\u25B2",
  chevronClosed: "\u25BC",
  transparencyToggleLabel: "Data transparency details",
  versionLabel: "App version",
} as const;
