export const mapCopy = {
  mapLabel: "Map showing nearby flagged businesses",
  searchPlaceholder: "Search a business name...",
  searchLabel: "Search for a business",
  searchHint: "Type a business name and press search to check its political donations",
  scanning: "Scanning\u2026",
  search: "Search",
  scanIcon: "\u2315",
  scanningIcon: "\u2026",
  zoomIn: "+",
  zoomOut: "\u2212",
  zoomInLabel: "Zoom in",
  zoomOutLabel: "Zoom out",
  locationLabel: "Center map on my location",
  loadingIcon: "\u2026",
  mediumWarning: "\u26A0 MEDIUM confidence \u2014 verify before acting.",
  fecLink: "See full FEC record \u2192",
  fecLinkLabel: "See full FEC record on fec.gov",
  avoidLabel: "AVOIDED",
  avoidConfirmed: "\u2713 AVOIDED",
  avoidRetry: "Try again",
  avoidMarkLabel: "Mark as avoided",
  avoidDoneLabel: "Avoided \u2014 confirmed",
  avoidRetryLabel: "Avoid failed \u2014 try again",
  markerAvoided: (name: string) => `Avoided: ${name}`,
  markerFlagged: (name: string, confidenceLabel: string) => `Flagged business: ${name}. Confidence: ${confidenceLabel}. Tap for details.`,
  tapLoading: "Searching nearby businesses",
  noMatch: (text: string) => `\u201C${text}\u201D \u2014 not confidently matched. `,
  lookupFailed: (text: string) => `Couldn\u2019t check \u201C${text}\u201D \u2014 try again later. `,
  fecSearch: "Search FEC.gov \u2197",
  fecSearchLabel: "Search FEC.gov directly",
  chooserHeading: (n: number) => `${n} MATCHES FOUND`,
  chooserRow: (name: string) => `View ${name}`,
  chooserDismiss: "Dismiss match chooser",
} as const;
