export const mapCopy = {
  tabLabel: "MAP",
  mapLabel: "Map showing nearby businesses with political funding on file",
  searchPlaceholder: "Search a business name...",
  searchLabel: "Search for a business",
  searchHint: "Search a business to see its political funding record",
  scanning: "Scanning\u2026",
  search: "Search",
  scanIcon: "\u2315",
  scanningIcon: "\u2026",
  zoomIn: "+",
  zoomOut: "\u2212",
  zoomInLabel: "Zoom in",
  zoomOutLabel: "Zoom out",
  locationLabel: "Center map on my location",
  loadingIcon: "\u2026",
  mediumWarning: "\u26A0 MEDIUM confidence \u2014 verify before acting.",
  pacDataLine: (committeeName: string) => `Data: ${committeeName}`,
  parentAttribution: (parentName: string) => `via ${parentName}`,
  fecLink: "See full FEC record \u2192",
  fecLinkLabel: "See full FEC record on fec.gov",
  avoidLabel: "AVOID",
  avoidConfirmed: "\u2713 AVOIDED",
  avoidRetry: "Try again",
  avoidMarkLabel: "Mark as avoided",
  avoidDoneLabel: "Avoided \u2014 confirmed",
  avoidRetryLabel: "Avoid failed \u2014 try again",
  markerAvoided: (name: string) => `Avoided: ${name}`,
  markerFlagged: (name: string, confidenceLabel: string) =>
    `Business with political funding on file: ${name}. Confidence: ${confidenceLabel}. Tap for details.`,
  tapLoading: "Searching nearby businesses",
  tapNoMatch: "No match found",
  noMatch: (text: string) => `No FEC record found for \u201C${text}\u201D.`,
  lookupFailed: (text: string) => `Couldn\u2019t reach FEC.gov for \u201C${text}\u201D. Try again later.`,
  fecSearch: "Search FEC.gov \u2197",
  fecSearchLabel: "Search FEC.gov directly",
  chooserHeading: (n: number) => `${n} MATCHES FOUND`,
  chooserRow: (name: string) => `View ${name}`,
  chooserDismiss: "Dismiss match chooser",
  barcodeButton: "UPC",
  barcodeScannerTitle: "Scan product barcode",
  barcodePreparing: "Preparing scanner\u2026",
  barcodeGuide: "Center a UPC or EAN code inside the frame.",
  barcodeResolving: "Resolving brand\u2026",
  barcodePermissionTitle: "Camera access needed",
  barcodePermissionBody: "Allow camera access to scan product barcodes in-store.",
  barcodePermissionDeniedBody: "Camera access is off for this app. Enable it in Settings to scan product barcodes.",
  barcodePermissionAction: "Allow camera",
  barcodePermissionActionLabel: "Grant camera access to scan barcodes",
  barcodeSettingsAction: "Open settings",
  barcodeSettingsActionLabel: "Open device settings to enable camera access",
  barcodeUnavailableTitle: "Camera unavailable",
  barcodeUnavailableBody: "Camera not available. Check your device settings.",
  barcodeFallbackLabel: "barcode",
  barcodeNoMatch: (label: string) => `Couldn\u2019t trace \u201C${label}\u201D to a company in our records.`,
  barcodeNotInDatabase: (label: string) => `Product not found in the barcode database for \u201C${label}\u201D.`,
  barcodeLookupFailed: (label: string) => `Barcode lookup failed for \u201C${label}\u201D. Try again in a moment.`,
  barcodeUnsupported: (label: string) => `\u201C${label}\u201D isn\u2019t a supported barcode type. Try a UPC or EAN code.`,
  barcodeContextEyebrow: "SCANNED PRODUCT",
  barcodeContextLine: (label: string, barcode: string) => `${label} \u00b7 BARCODE ${barcode}`,
  // Banner states
  bannerNoMatch: (text: string) => `No FEC record for \u201C${text}\u201D.`,
  bannerLookupFailed: (text: string) => `Couldn\u2019t reach FEC.gov for \u201C${text}\u201D. Try again later.`,
  bannerNoPac: (name: string) => `${name} has no corporate PAC on file.`,
  bannerDissolved: (name: string) => `${name}\u2019s PAC is dissolved. No recorded activity.`,
  bannerDismissLabel: "Dismiss banner",
  // DataZone
  dataZoneDetail: "See full breakdown \u2192",
  dataZoneDetailLabel: "See full FEC breakdown",
  // Barcode scanner — screen reader
  barcodeCameraLabel: "Camera viewfinder for barcode scanning",
  // Chooser — screen reader
  chooserModalLabel: "Choose which business to view",
  // Confidence badge
  confidenceBadgeHint: "Tap to learn what medium confidence means",
  confidenceAlertTitle: "\u26A0 Medium Confidence",
  confidenceAlertBody: "This match was found in FEC records but the name similarity is below our high-confidence threshold. The data is real \u2014 verify the business name before acting.",
  // Card — screen reader
  cardAvoidedAnnouncement: "Avoided. Nice!",
  cardModalLabel: "Business detail card",
  // First-use hints (persist dismissal via SecureStore)
  hintSearch: "Search a business or tap on the map to see its political funding.",
  hintTap: "Tap any business on the map to pull up its record.",
  hintBarcode: "Use the UPC button to scan a product barcode.",
  hintDismissLabel: "Dismiss hint",
} as const;
