export const mapCopy = {
  mapLabel: "Map showing nearby flagged businesses",
  searchPlaceholder: "Search a business name...",
  searchLabel: "Search for a business",
  searchHint: "Type a business name and press search to check its FEC donation record",
  scanning: "Scanning\u2026",
  search: "Search",
  scanIcon: "\u2315",
  scanningIcon: "\u2026",
  zoomIn: "+",
  zoomOut: "\u2212",
  zoomInLabel: "Zoom in",
  zoomOutLabel: "Zoom out",
  locationLabel: "Center map on my location",
  loadingIcon: "\u2026",
  mediumWarning: "\u26A0 MEDIUM confidence \u2014 verify before acting.",
  pacDataLine: (committeeName: string) => `Data: ${committeeName}`,
  parentAttribution: (parentName: string) => `via ${parentName}`,
  fecLink: "See full FEC record \u2192",
  fecLinkLabel: "See full FEC record on fec.gov",
  avoidLabel: "AVOID",
  avoidConfirmed: "\u2713 AVOIDED",
  avoidRetry: "Try again",
  avoidMarkLabel: "Mark as avoided",
  avoidDoneLabel: "Avoided \u2014 confirmed",
  avoidRetryLabel: "Avoid failed \u2014 try again",
  markerAvoided: (name: string) => `Avoided: ${name}`,
  markerFlagged: (name: string, confidenceLabel: string) => `Flagged business: ${name}. Confidence: ${confidenceLabel}. Tap for details.`,
  tapLoading: "Searching nearby businesses",
  tapNoMatch: "No match found",
  noMatch: (text: string) => `Couldn\u2019t match \u201C${text}\u201D to an FEC filing.`,
  lookupFailed: (text: string) => `FEC.gov lookup failed for \u201C${text}\u201D \u2014 try again later.`,
  fecSearch: "Search FEC.gov \u2197",
  fecSearchLabel: "Search FEC.gov directly",
  chooserHeading: (n: number) => `${n} MATCHES FOUND`,
  chooserRow: (name: string) => `View ${name}`,
  chooserDismiss: "Dismiss match chooser",
  barcodeButton: "UPC",
  barcodeScannerTitle: "Scan product barcode",
  barcodePreparing: "Preparing scanner\u2026",
  barcodeGuide: "Center a UPC or EAN code inside the frame.",
  barcodeResolving: "Resolving brand\u2026",
  barcodePermissionTitle: "Camera access needed",
  barcodePermissionBody: "Allow camera access to scan product barcodes in-store.",
  barcodePermissionDeniedBody: "Camera access is off for this app. Enable it in Settings to scan product barcodes.",
  barcodePermissionAction: "Allow camera",
  barcodeSettingsAction: "Open settings",
  barcodeUnavailableTitle: "Camera unavailable",
  barcodeUnavailableBody: "This runtime can’t open the camera scanner. Rebuild the app or try on a physical device.",
  barcodeFallbackLabel: "barcode",
  barcodeNoMatch: (label: string) => `Couldn\u2019t map \u201C${label}\u201D to a tracked parent company.`,
  barcodeLookupFailed: (label: string) => `Barcode lookup failed for \u201C${label}\u201D. Try again in a moment.`,
  barcodeUnsupported: (label: string) => `\u201C${label}\u201D isn\u2019t a supported retail barcode. Try a UPC or EAN code.`,
  barcodeContextEyebrow: "SCANNED PRODUCT",
  barcodeContextLine: (label: string, barcode: string) => `${label} \u00b7 BARCODE ${barcode}`,
  // Banner states — lightweight dismissible bar for non-card results
  bannerNoMatch: (text: string) => `No FEC match for \u201C${text}\u201D.`,
  bannerLookupFailed: (text: string) => `Lookup failed for \u201C${text}\u201D \u2014 try again later.`,
  bannerNoPac: (name: string) => `${name} has no corporate PAC on file.`,
  bannerDissolved: (name: string) => `${name}\u2019s PAC is dissolved with no recorded donations.`,
  bannerDismissLabel: "Dismiss banner",
  // DataZone
  dataZoneDetail: "See full breakdown \u2192",
  dataZoneDetailLabel: "See full FEC breakdown",
  // Card — screen reader
  cardAvoidedAnnouncement: (name: string) => `Avoided ${name}. Well done.`,
  cardModalLabel: "Business detail card",
} as const;
