export const onboardCopy = {
  welcomeTitle: "WELCOME",
  letsGo: "PRESS START",
  appDisplay: "F*CK\nFASCISTS",
  tagline: "The fascists won\u2019t\nf*ck themselves. \uD83E\uDD18",
  body: "Look up businesses. See who they fund. Decide where to spend.",
  note: "Open-source \u00b7 Nonprofit \u00b7 No tracking",
  welcomeKicker: "LET\u2019S GO!!!!",
  howTitle: "HOW IT WORKS",
  mapTitle: "MAP",
  mapDesc: "Scan nearby businesses. Flag GOP donors on your map. Tap AVOID and move on.",
  surveyTitle: "TRACK",
  surveyDesc: "Did you skip Amazon, Instagram, or X this week? Check them off.",
  reportTitle: "SCORECARD",
  reportDesc: "Every Friday, see who you didn\u2019t fund this week. Share it if you want.",
  locTitle: "FIND NEARBY BUSINESSES",
  locIcon: "[PIN]",
  locWhy: "We use your location to center the map on your neighborhood so you can spot flagged businesses nearby.",
  locPromise: "Your GPS coordinates are held in memory only \u2014 never stored, never transmitted. We derive a rough area code for caching. That\u2019s it.",
  locBtn: "ALLOW LOCATION",
  notifTitle: "NEVER MISS THE DROP",
  notifIcon: "[!]",
  notifWhy: "Your weekly scorecard drops every Friday. We\u2019ll let you know when it\u2019s ready.",
  notifPromise: "Notifications are local-only and scheduled on your device. We never send push messages from a server.",
  notifBtn: "ALLOW NOTIFICATIONS",
  privacyTitle: "YOUR PRIVACY FIRST",
  noAccounts: "NO ACCOUNTS",
  noAccountsDesc: "No sign-in, no email, no user ID. Ever.",
  noLocation: "NO LOCATION STORAGE",
  noLocationDesc: "GPS is session-only. Coordinates are never written to disk.",
  noHistory: "NO HISTORY",
  noHistoryDesc: "The app never records which businesses you visited or used \u2014 only the ones you actively avoided.",
  onDevice: "ON-DEVICE ONLY",
  onDeviceDesc: "All data stays on your phone. No servers, no syncing.",
  openSource: "OPEN SOURCE",
  openSourceDesc: "Every line of code is public. Check it yourself.",
  fecData: "DATA: FEC.GOV",
  fecDataDesc: "Donation data comes directly from the Federal Election Commission \u2014 the official US government source for campaign finance data.",
  ourPromise: "OUR PROMISE",
  requesting: "...",
  next: "NEXT",
  skip: "SKIP FOR NOW",
  progressStep: (n: number, total: number) => `Step ${n} of ${total}`,
  mapIcon: "[+]",
  surveyIcon: "[\u2713]",
  reportIcon: "[\u2605]",
} as const;
