export const onboardCopy = {
  welcomeTitle: "WELCOME",
  letsGo: "LET'S GO",
  appDisplay: "F*CK\nFASCISTS",
  tagline: "Your money.\nYour power.\nYour choice.",
  body: "Every dollar you spend is a vote. This app helps you avoid businesses and platforms that fund Republican campaigns and authoritarian politics \u2014 and celebrate the times you do.",
  note: "Open-source \u00b7 Nonprofit \u00b7 Privacy-first",
  howTitle: "HOW IT WORKS",
  mapTitle: "MAP",
  mapDesc: "Scan nearby businesses. Flag GOP donors on your map. Tap AVOIDED and move on.",
  surveyTitle: "WEEKLY SURVEY",
  surveyDesc: "Check off the platforms and services you skipped this week.",
  reportTitle: "REPORT CARD",
  reportDesc: "Every Friday, your weekly impact drops \u2014 see it, share it, own it.",
  locTitle: "FIND NEARBY BUSINESSES",
  locIcon: "[PIN]",
  locWhy: "We use your location to center the map on your neighborhood so you can spot flagged businesses nearby.",
  locPromise: "Your GPS coordinates are held in memory only \u2014 never stored, never transmitted. We derive a rough area code for caching. That\u2019s it.",
  locBtn: "ALLOW LOCATION",
  notifTitle: "NEVER MISS THE DROP",
  notifIcon: "[!]",
  notifWhy: "Your weekly report card drops at a synchronized moment every Friday. Enable notifications so you never miss it.",
  notifPromise: "Notifications are local-only and scheduled on your device. We never send push messages from a server.",
  notifBtn: "ALLOW NOTIFICATIONS",
  privacyTitle: "YOUR PRIVACY FIRST",
  noAccounts: "NO ACCOUNTS",
  noAccountsDesc: "No sign-in, no email, no user ID. Ever.",
  noLocation: "NO LOCATION STORAGE",
  noLocationDesc: "GPS is session-only. Coordinates are never written to disk.",
  noHistory: "NO HISTORY",
  noHistoryDesc: "The app never records which businesses you visited or used \u2014 only the ones you actively avoided.",
  onDevice: "ON-DEVICE ONLY",
  onDeviceDesc: "All data stays on your phone. No backend, no syncing in v1.",
  openSource: "OPEN SOURCE",
  openSourceDesc: "Every line of code is public. Check it yourself.",
  fecData: "DATA: FEC.GOV",
  fecDataDesc: "Donation data comes directly from the Federal Election Commission \u2014 the official US government source for campaign finance data.",
  ourPromise: "OUR PROMISE",
  requesting: "...",
  next: "NEXT",
  skip: "SKIP FOR NOW",
  progressStep: (n: number, total: number) => `Step ${n} of ${total}`,
  mapIcon: "[+]",
  surveyIcon: "[\u2713]",
  reportIcon: "[\u2605]",
} as const;
