export const scorecardCopy = {
  tabLabel: "SCORECARD",
  title: "SCORECARD",
  dateRange: (range: string) => range,
  totalCount: (n: number) => `${n}\u00d7`,
  framingLine: "I f*cked...",
  personCount: (n: number) => `${n}\u00d7`,
  sourceSkipped: (name: string, count: number) => `skipped ${name} ${count}\u00d7`,
  sourceAvoided: (name: string, count: number) => `avoided ${name} ${count}\u00d7`,
  sourceWalkedPast: (name: string, count: number) => `walked past ${name} ${count}\u00d7`,
  sourceStayedOff: (name: string, count: number) => `stayed off ${name} ${count}\u00d7`,
  othersLine: (n: number) => `+ ${n} others`,
  dropTime: (time: string) => `DROPS ${time}`,
  shareHeader: "F*CK FASCISTS \u2014 Scorecard",
  shareBtn: "SHARE",
  shareLabel: "Share your scorecard",
  previewBtn: "PREVIEW",
  previewLabel: "Preview your scorecard early",
  previewStamp: "PREVIEW",
  previewA11y: "Preview \u2014 this is not the official weekly drop",
  emptyMap: "Map",
  emptyTrack: "Track",
  emptyBefore: "Hit the ",
  emptyMiddle: ". Hit ",
  emptyAfter: ".\nMake them feel it.",
  tagline: "The fascists won\u2019t f*ck themselves. \uD83E\uDD18",
  cta: "try it at fuckfascists.org",
  dataAttribution: "DATA: FEC.GOV",
  loadingLabel: "Loading scorecard",
} as const;
