import { sharedCopy } from './shared';

export const scorecardCopy = {
  tabLabel: "SCORECARD",
  title: "SCORECARD",
  dateRange: (range: string) => range,
  totalCount: (n: number) => `${n}\u00d7`,
  framingLine: "I f*cked...",
  personCount: (n: number) => `${n}\u00d7`,
  sourceLine: (name: string, count: number) => `f*cked ${name} ${count}\u00d7`,
  othersLine: (n: number) => `+ ${n} others`,
  dropTime: (time: string) => `READY ${time}`,
  shareHeader: "FCK FASCISTS",
  shareBtn: "SHARE",
  shareLabel: "Share your scorecard",
  previewBtn: "PREVIEW",
  previewLabel: "Preview your scorecard early",
  previewStamp: "PREVIEW",
  previewA11y: "Preview \u2014 this is not the weekly scorecard",
  emptyTitle: "NO ONE. YET.",
  emptyBody: "Hit the {map}. Hit {track}.\nGive us something to work with.",
  tagline: "The fascists won\u2019t f*ck themselves. \uD83E\uDD18\uD83C\uDFFD",
  cta: sharedCopy.siteUrl,
  dataAttribution: "DATA: FEC.GOV",
  loadingLabel: "Loading scorecard",
} as const;
