export const scorecardCopy = {
  title: "SCORECARD",
  subtitle: "WEEKLY SCORECARD",
  shareHeader: "F*CK FASCISTS \u2014 Weekly Scorecard",
  shareBtn: "SHARE",
  shareLabel: "Share your scorecard",
  previewBtn: "PREVIEW",
  previewLabel: "Preview your scorecard early",
  previewStamp: "PREVIEW",
  previewA11y: "Preview \u2014 this is not the official weekly drop",
  dropTime: (time: string) => `DROPS ${time}`,
  entityCount: (n: number) => `${n} business avoidances`,
  platformCount: (n: number) => `${n} platforms avoided`,
  topEntities: (names: string) => `Top: ${names}`,
  entityTile: "BUSINESS\nAVOIDED",
  platformTile: "PLATFORMS\nAVOIDED",
  entitySection: "BUSINESSES",
  platformSection: "PLATFORMS",
  emptyState: "YOUR MONEY IS STILL\nFUNDING FASCISTS.\n\nHit the Map. Hit Track.\nMake them feel it.",
  footer: "fuckfascists.org \u00b7 DATA: FEC.GOV",
} as const;
