export const sharedCopy = {
  appName: "FCK FASCISTS",
  siteUrl: "fckfascists.com",
  repoUrl: "https://github.com/idontlikecodemuch/fuckfascists",
  dataRepoUrl: "https://github.com/idontlikecodemuch/fckfascists-data",
  issuesUrl: "https://github.com/idontlikecodemuch/fuckfascists/issues",
  privacyUrl: "https://github.com/idontlikecodemuch/fuckfascists/blob/main/PRIVACY.md",
  contactEmail: "[need to change!!]",
  extensionChromeUrl: "[need to change!!]",
  extensionFirefoxUrl: "[need to change!!]",
  dismiss: "DISMISS",
  dismissLabel: "Dismiss",
  partyR: "R:",
  partyD: "D:",
  verified: "VERIFIED",
  matched: "MATCHED",
  confidenceHigh: "HIGH",
  confidenceMedium: "MEDIUM",
  warningIcon: "\u26A0",
  checkmark: "\u2713",
  donationUnavail: "Donation data not available.",
  donationNoneOnFile: "No donation data on file.",
  totalSince: (rAmt: string, dAmt: string) => `Total since 2016: R: ${rAmt} \u00b7 D: ${dAmt}`,
  activeCycles: (cycles: string) => `Active cycles: ${cycles}`,
  confidenceA11y: (label: string) => `Confidence: ${label}`,
  totalSince2016: "TOTAL SINCE 2016",
  recentCycleShort: (rAmt: string, dAmt: string, cycle: string) => `Recent (${cycle}): R: ${rAmt} \u00b7 D: ${dAmt}`,
} as const;
