// Auto-generated from copy-all.json — do not edit directly.
var COPY_ALL_DATA = {
  "shared": {
    "appName": "F*CK FASCISTS",
    "dismiss": "DISMISS",
    "dismissLabel": "Dismiss",
    "gop": "GOP",
    "dem": "DEM",
    "verified": "VERIFIED",
    "matched": "MATCHED",
    "confidenceHigh": "HIGH",
    "confidenceMedium": "MEDIUM",
    "warningIcon": "⚠",
    "checkmark": "✓",
    "siteUrl": "fuckfascists.org",
    "donationUnavail": "Donation data temporarily unavailable.",
    "donationNoneOnFile": "No donation data on file.",
    "totalSince": "Total since 2016: GOP {gopAmt}·DEM {demAmt}",
    "activeCycles": "Active cycles: {cycles}",
    "confidenceA11y": "Confidence: {label}",
    "totalSince2016": "TOTAL SINCE 2016",
    "recentCycleShort": "Recent ({cycle}): GOP {gopAmt}·DEM {demAmt}"
  },
  "map": {
    "tabLabel": "MAP",
    "mapLabel": "Map showing nearby flagged businesses",
    "searchPlaceholder": "Search a business name...",
    "searchLabel": "Search for a business",
    "searchHint": "Type a business name and press search to check its FEC donation record",
    "scanning": "Scanning…",
    "search": "Search",
    "scanIcon": "⌕",
    "scanningIcon": "…",
    "zoomIn": "+",
    "zoomOut": "−",
    "zoomInLabel": "Zoom in",
    "zoomOutLabel": "Zoom out",
    "locationLabel": "Center map on my location",
    "loadingIcon": "…",
    "mediumWarning": "⚠ MEDIUM confidence — verify before acting.",
    "pacDataLine": "Data: {committeeName}",
    "parentAttribution": "via {parentName}",
    "fecLink": "See full FEC record →",
    "fecLinkLabel": "See full FEC record on fec.gov",
    "avoidLabel": "AVOID",
    "avoidConfirmed": "✓ AVOIDED",
    "avoidRetry": "Try again",
    "avoidMarkLabel": "Mark as avoided",
    "avoidDoneLabel": "Avoided — confirmed",
    "avoidRetryLabel": "Avoid failed — try again",
    "markerAvoided": "Avoided: {name}",
    "markerFlagged": "Flagged business: {name}. Confidence: {confidenceLabel}. Tap for details.",
    "tapLoading": "Searching nearby businesses",
    "tapNoMatch": "No match found",
    "noMatch": "Couldn't match \"{text}\" to an FEC filing.",
    "lookupFailed": "FEC.gov lookup failed for \"{text}\" — try again later.",
    "fecSearch": "Search FEC.gov ↗",
    "fecSearchLabel": "Search FEC.gov directly",
    "chooserHeading": "{n} MATCHES FOUND",
    "chooserRow": "View {name}",
    "chooserDismiss": "Dismiss match chooser",
    "barcodeButton": "UPC",
    "barcodeScannerTitle": "Scan product barcode",
    "barcodePreparing": "Preparing scanner…",
    "barcodeGuide": "Center a UPC or EAN code inside the frame.",
    "barcodeResolving": "Resolving brand…",
    "barcodePermissionTitle": "Camera access needed",
    "barcodePermissionBody": "Allow camera access to scan product barcodes in-store.",
    "barcodePermissionDeniedBody": "Camera access is off for this app. Enable it in Settings to scan product barcodes.",
    "barcodePermissionAction": "Allow camera",
    "barcodePermissionActionLabel": "Grant camera access to scan barcodes",
    "barcodeSettingsAction": "Open settings",
    "barcodeSettingsActionLabel": "Open device settings to enable camera access",
    "barcodeUnavailableTitle": "Camera unavailable",
    "barcodeUnavailableBody": "This runtime can't open the camera scanner. Rebuild the app or try on a physical device.",
    "barcodeFallbackLabel": "barcode",
    "barcodeNoMatch": "Couldn't map \"{label}\" to a tracked parent company.",
    "barcodeLookupFailed": "Barcode lookup failed for \"{label}\". Try again in a moment.",
    "barcodeUnsupported": "\"{label}\" isn't a supported retail barcode. Try a UPC or EAN code.",
    "barcodeContextEyebrow": "SCANNED PRODUCT",
    "barcodeContextLine": "{label} · BARCODE {barcode}",
    "bannerNoMatch": "No FEC match for \"{text}\".",
    "bannerLookupFailed": "Lookup failed for \"{text}\" — try again later.",
    "bannerNoPac": "{name} has no corporate PAC on file.",
    "bannerDissolved": "{name}'s PAC is dissolved with no recorded donations.",
    "bannerDismissLabel": "Dismiss banner",
    "dataZoneDetail": "See full breakdown →",
    "dataZoneDetailLabel": "See full FEC breakdown",
    "barcodeCameraLabel": "Camera viewfinder for barcode scanning",
    "chooserModalLabel": "Choose which business to view",
    "cardAvoidedAnnouncement": "Avoided {name}. Well done.",
    "cardModalLabel": "Business detail card"
  },
  "platforms": {
    "tabLabel": "TRACK",
    "weekLabel": "Week of {weekOf}",
    "editPlatforms": "Edit platforms",
    "editPlatformsA11y": "Edit platform selection",
    "avoidCountLabel": "{n}× avoids this week",
    "pumpUp": "LET'S GO!!!!",
    "loading": "Loading platform data",
    "checklist": "Platform checklist",
    "avoidBtn": "AVOID",
    "avoidedBtn": "✓",
    "avoidBtnA11y": "Avoid {name} today",
    "avoidedBtnA11y": "{name} avoided today. Tap to expand day details.",
    "countLabel": "{n}×",
    "countDash": "—",
    "countA11y": "Avoided {name} {n} time(s) this week",
    "expandIndicator": "+",
    "collapseIndicator": "−",
    "rowSubtitle": "{company} · CEO: {ceo}",
    "setupTitle": "SELECT YOUR TARGETS",
    "setupSubhead": "Choose the platforms you want to track. You can change this anytime.",
    "setupDone": "DONE",
    "dayLabels": "M, T, W, T, F, S, S",
    "dayCheckedLabel": "{day}: {name} avoided",
    "dayUncheckedLabel": "{day}: Tap to log {name} avoidance",
    "dayFutureLabel": "{day}: Future",
    "expandLabel": "Expand {name} day details",
    "collapseLabel": "Collapse {name} day details",
    "groupHeaderA11y": "{name} — {total}× this week",
    "spriteReactions": "ow!, stop!, no!, hey!",
    "arenaTapA11y": "{name} sprite. Tap for reaction.",
    "shortParentNames.Meta Platforms": "META",
    "shortParentNames.Amazon.com Inc": "AMAZON",
    "shortParentNames.Alphabet Inc": "ALPHABET",
    "shortParentNames.X Corp": "X CORP",
    "clearData": "Clear data",
    "clearDataA11y": "Clear all platform avoid data",
    "clearDataConfirm": "All avoid data cleared.",
    "nudgeTitle": "Your card drops tomorrow.",
    "nudgeBody": "Any more fascists you f*cked this week?",
    "nudgeBanner": "Scorecard drops tomorrow — log your avoids!",
    "nudgeDismiss": "DISMISS",
    "nudgeDismissA11y": "Dismiss nudge banner"
  },
  "scorecard": {
    "tabLabel": "SCORECARD",
    "title": "SCORECARD",
    "dateRange": "{range}",
    "totalCount": "{n}×",
    "framingLine": "I f*cked...",
    "personCount": "{n}×",
    "sourceSkipped": "skipped {name} {count}×",
    "sourceAvoided": "avoided {name} {count}×",
    "sourceWalkedPast": "walked past {name} {count}×",
    "sourceStayedOff": "stayed off {name} {count}×",
    "othersLine": "+ {n} others",
    "dropTime": "DROPS {time}",
    "shareHeader": "F*CK FASCISTS — Scorecard",
    "shareBtn": "SHARE",
    "shareLabel": "Share your scorecard",
    "previewBtn": "PREVIEW",
    "previewLabel": "Preview your scorecard early",
    "previewStamp": "PREVIEW",
    "previewA11y": "Preview — this is not the official weekly drop",
    "emptyMap": "Map",
    "emptyTrack": "Track",
    "emptyBefore": "Hit the ",
    "emptyMiddle": ". Hit ",
    "emptyAfter": ".\nMake them feel it.",
    "tagline": "The fascists won't f*ck themselves. 🤌",
    "cta": "try it at fuckfascists.org",
    "dataAttribution": "DATA: FEC.GOV",
    "loadingLabel": "Loading scorecard"
  },
  "onboard": {
    "welcomeTitle": "WELCOME",
    "letsGo": "PRESS START",
    "appDisplay": "F*CK\nFASCISTS",
    "tagline": "The fascists won't\nf*ck themselves. 🤌",
    "body": "Look up businesses. See who they fund. Decide where to spend.",
    "note": "Open-source · Nonprofit · No tracking",
    "featureMap": "MAP — Flag GOP donors near you",
    "featureTrack": "TRACK — Log the platforms you skipped",
    "featureScorecard": "SCORECARD — See your impact every Friday",
    "permissionsTitle": "SET UP",
    "locTitle": "FIND NEARBY BUSINESSES",
    "locWhy": "We use your location to center the map on your neighborhood.",
    "locPromise": "GPS is session-only — never stored, never transmitted.",
    "locBtn": "ALLOW LOCATION",
    "notifTitle": "NEVER MISS THE DROP",
    "notifWhy": "Your weekly scorecard drops every Friday.",
    "notifPromise": "Notifications are local-only. No server push.",
    "notifBtn": "ALLOW NOTIFICATIONS",
    "privacyTitle": "YOUR DATA",
    "noAccounts": "NO ACCOUNTS",
    "noAccountsDesc": "No sign-in, no email, no user ID. Ever.",
    "noLocation": "NO LOCATION STORAGE",
    "noLocationDesc": "GPS is session-only. Coordinates never written to disk.",
    "noHistory": "NO HISTORY",
    "noHistoryDesc": "Only records what you actively avoided — never what you visited.",
    "onDevice": "ON-DEVICE ONLY",
    "onDeviceDesc": "All data stays on your phone. No servers, no syncing.",
    "openSource": "OPEN SOURCE",
    "openSourceDesc": "Every line of code is public.",
    "ourPromise": "OUR PROMISE",
    "requesting": "...",
    "confirmed": "GRANTED",
    "next": "NEXT",
    "skip": "SKIP",
    "done": "LET'S GO",
    "progressStep": "Step {n} of {total}"
  },
  "info": {
    "tabLabel": "INFO",
    "title": "INFO",
    "about": "ABOUT",
    "data": "HOW IT WORKS",
    "faq": "FAQ",
    "links": "LINKS & SOURCE",
    "linkText": "{label} ↗",
    "linkLabel": "{label} — opens in browser",
    "faqCollapse": "Tap to collapse",
    "faqExpand": "Tap to expand answer",
    "chevronOpen": "▲",
    "chevronClosed": "▼",
    "transparencyToggleLabel": "Data transparency details",
    "versionLabel": "App version"
  },
  "infoContent": {
    "version": "1.0.0",
    "about.tagline": "The fascists won't f*ck themselves. 🤌",
    "about.description": "Look up businesses. See who they fund. Decide where to spend.",
    "about.organization": "Open-source nonprofit project. See the repo for governance details.",
    "about.sourceCodeUrl": "https://github.com/idontlikecodemuch/fuckfascists",
    "transparency.data-source.title": "Where does the data come from?",
    "transparency.data-source.body": "All donation figures come directly from the Federal Election Commission (FEC) — the official US government source for campaign finance data, available at fec.gov. Every dollar figure shown in the app links back to its original FEC filing.",
    "transparency.fec-filings.title": "Can I verify the numbers myself?",
    "transparency.fec-filings.body": "Yes — every donation figure links directly to the original FEC filing at fec.gov, the authoritative government source. Tap 'See full FEC record' on any business card to open the committee's official page. You can verify every number yourself without taking our word for it.",
    "transparency.confidence.title": "What does the MATCHED badge mean?",
    "transparency.confidence.body": "When you look up a business, we match its name against the FEC committee database. Most businesses match with high confidence and show no badge. When we're less certain, a MATCHED badge and disclaimer appear — always with a link to verify on FEC.gov. We never claim more certainty than the data supports.",
    "transparency.entity-list.title": "What is the curated entity list?",
    "transparency.entity-list.body": "A community-maintained JSON file covering the top GOP-donating companies, retailers, and platforms. It ships with the app for offline use and updates automatically from GitHub. Anyone can submit corrections or additions via a pull request.",
    "transparency.storage.title": "What does the app store on my device?",
    "transparency.storage.body": "Only avoidance actions you explicitly take: the business IDs and dates you tapped Avoid (no times, no locations), and the platform avoid events you logged. Nothing else. No coordinates, no browsing history, no identifiers.",
    "transparency.no-server.title": "Is there a server?",
    "transparency.no-server.body": "The only outbound calls are to the FEC API (from your device directly) and to fetch the entity list / drop schedule from GitHub. There is no backend, no telemetry, and no analytics.",
    "faq.trust.q": "Why should I trust this data?",
    "faq.trust.a": "Every figure comes directly from FEC.gov — the official US government record of campaign finance. Uncertain matches are always labeled and link directly to FEC.gov so you can verify. We never show data we cannot cite.",
    "faq.wrong-match.q": "What if a business is misidentified?",
    "faq.wrong-match.a": "MEDIUM-confidence matches always show a \"verify before acting\" warning. Tap the FEC.gov link to check the source yourself. If something is wrong, please open an issue or PR in the data repo — the community maintains the entity list.",
    "faq.tracking.q": "Does the app track me?",
    "faq.tracking.a": "No. There are no accounts, no user IDs, and no analytics. Your GPS is accessed only when you tap the locate button and is never written to disk. The browser extension never stores which sites you visit.",
    "faq.why-republican.q": "Why focus on Republican donations?",
    "faq.why-republican.a": "The app is built on the premise that donations to the Republican Party and aligned PACs since 2015 have funded an authoritarian political project. Users can review the data and draw their own conclusions — every figure links to its source on FEC.gov so nothing is taken on faith.",
    "faq.add-business.q": "Can I add a business or correct an entry?",
    "faq.add-business.a": "Yes. The entity list is open-source on GitHub. Open a pull request with the canonical name, aliases, domains, and FEC committee ID. The community reviews all submissions.",
    "faq.matched-badge.q": "What does the MATCHED badge mean?",
    "faq.matched-badge.a": "Tap 'See full FEC record' on the business card and verify the match yourself before tapping Avoid. MATCHED means the name similarity is strong but not conclusive.",
    "faq.free.q": "Is this free?",
    "faq.free.a": "Yes, always. The app is a nonprofit project. There are no subscriptions, no ads, and no in-app purchases. Donations to support the project are welcome — details in the GitHub repo.",
    "faq.extension-sync.q": "Why doesn't the browser extension sync with the app?",
    "faq.extension-sync.a": "Cross-device sync requires a backend, which we deliberately do not have. The extension has its own weekly summary in the popup. Sync is planned once a privacy-preserving architecture is designed.",
    "faq.internet.q": "Does the app need internet?",
    "faq.internet.a": "Most data is bundled with the app and works offline. Some lookups check FEC.gov directly, which requires a connection.",
    "faq.edit-platforms.q": "How do I edit my platform list?",
    "faq.edit-platforms.a": "Tap EDIT at the top of the Platforms tab. You can add or remove platforms anytime. Your selections carry over week to week.",
    "links.fec.label": "FEC.gov (campaign finance data)",
    "links.fec.url": "https://www.fec.gov",
    "links.source-code.label": "Source code (GitHub)",
    "links.source-code.url": "https://github.com/idontlikecodemuch/fuckfascists",
    "links.data-repo.label": "Entity list (GitHub)",
    "links.data-repo.url": "https://github.com/idontlikecodemuch/fckfascists-data",
    "links.issues.label": "Report a bug or correction",
    "links.issues.url": "https://github.com/idontlikecodemuch/fuckfascists/issues",
    "links.privacy.label": "Privacy policy",
    "links.privacy.url": "https://github.com/idontlikecodemuch/fuckfascists/blob/main/PRIVACY.md"
  },
  "launch": {
    "tapToStart": "PRESS START",
    "tapLabel": "Tap anywhere to dismiss and enter the app",
    "messages.0": "Every dollar is a vote.",
    "messages.1": "They count on you forgetting.",
    "messages.2": "Silence is a donation.",
    "messages.3": "Your wallet. Your power.",
    "messages.4": "Make them feel it.",
    "messages.5": "The fascists won't f*ck themselves.",
    "messages.6": "One tap at a time."
  },
  "beta": {
    "indicator": "BETA",
    "indicatorLabel": "Beta testing mode is active",
    "bugButton": "BUG",
    "bugButtonLabel": "Report a bug — captures screenshot",
    "resetButton": "RESET",
    "resetButtonLabel": "Reset app state for a fresh-install style test",
    "screenshotSaved": "Screenshot saved: {surface}",
    "screenshotFailed": "Could not save screenshot.",
    "resetConfirmTitle": "Reset app for testing?",
    "resetConfirmBody": "This clears onboarding, launch flags, platform setup, avoid history, and barcode cache so you can test from the beginning again.",
    "resetCancelAction": "Cancel",
    "resetConfirmAction": "Reset now",
    "resetDone": "App state reset. Fully close and reopen the app to start from onboarding again.",
    "resetFailed": "Could not reset app state.",
    "activated": "Beta mode ON",
    "deactivated": "Beta mode OFF",
    "surfaceLabel": "{tab}"
  },
  "scan": {
    "tabLabel": "SCAN BETA",
    "heading": "SCAN A PRODUCT",
    "body": "Point the camera at a UPC or EAN barcode. We resolve the product brand, map it to a parent company in the bundled entity list, and cache the result on this device.",
    "primaryAction": "OPEN SCANNER",
    "primaryActionLabel": "Open the barcode scanner camera",
    "busyAction": "LOOKING UP...",
    "busyActionLabel": "Looking up scanned barcode",
    "footnote": "Best results: fill the frame with the barcode and keep the phone steady."
  },
  "extension": {
    "appName": "F*CK FASCISTS",
    "cleanState": "No flagged entities detected on this page.",
    "donationUnavail": "Donation data temporarily unavailable.",
    "fecLink": "See FEC record ↗",
    "avoidBtn": "★ AVOIDED",
    "snoozeBtn": "ZZZ SNOOZE 7d",
    "avoidedTitle": "AVOIDED!",
    "avoidedSub": "This one counts.",
    "weeklyTitle": "THIS WEEK",
    "weeklyBiz": "BUSINESSES: ",
    "weeklyPlat": "PLATFORMS: ",
    "gopPrefix": "GOP ",
    "demSep": " · DEM ",
    "cyclePrefix": "in ",
    "totalPrefix": "Total since 2016: GOP ",
    "activeCycles": "Active cycles: ",
    "fecError": "Couldn't reach FEC — try again later.",
    "noBundledData": "No bundled donation data.",
    "confidenceHigh": "HIGH",
    "confidenceMedium": "MEDIUM",
    "mediumTitle": "MEDIUM confidence — data may not be exact. Always verify at FEC.",
    "mediumWarning": "MEDIUM confidence — verify before acting.",
    "weeklyTop": "TOP: "
  }
};
